# 1. Read image from webcam

Use this to take pictures using the webcam and store them in memory.

Commented code reads taken image and gives option to gray and rescale.

https://github.com/kevinam99/capturing-images-from-webcam-using-opencv-python

1. Run the file webcam-capture-v1.01.py by running the command python3 webcam-capture-v1.01.py
2. The webcam will start running.
3. Bring the picture that you want to save in the webcam frame.
4. Once the object is in the right frame, press the key 's' to save a picture.
5. If you want to quit, just press 'q'.
6. After hitting 's' to save the picture,you will get a view of the saved image which will automatically close in 1.6s and a new image file will be created in the same directory as that of the program. The image will be saved as saved_image.jpg
7. The file saved_image is furthered converted to grayscale and then resized to 28x28 size for further use in relevant programs, for example, machine learning, which was my primary requirement of creating this file.
8. Do not exit the program by stopping the command. This won't turn off the camera. If you do this, close the terminal to stop the camera from running.


In [8]:
import cv2 

key = cv2. waitKey(1)
webcam = cv2.VideoCapture(0)
while True:
     
    check, frame = webcam.read()
    print(check) #prints true as long as the webcam is running
    print(frame) #prints matrix values of each framecd 
    cv2.imshow("Capturing", frame)
    key = cv2.waitKey(1)
    if key == ord('s'): 
        cv2.imwrite(filename='/home/sarita/Documents/SeniorD/apriltag_detection/calibration_images/webcam/new_images/saved_img.jpg', img=frame)
        webcam.release()
#         img_new = cv2.imread('saved_img.jpg', cv2.IMREAD_GRAYSCALE)
#         img_new = cv2.imshow("Captured Image", img_new)
#         cv2.waitKey(1650)
        cv2.destroyAllWindows()
#         print("Processing image...")
#         img_ = cv2.imread('/home/sarita/Documents/SeniorD/apriltag_detection/calibration_images/webcam/new_images/saved_img.jpg', cv2.IMREAD_ANYCOLOR)
#         print("Converting RGB image to grayscale...")
#         img_ = cv2.cvtColor(img_, cv2.COLOR_BGR2GRAY)
#         print("Converted RGB image to grayscale...")
#         print("Resizing image to 28x28 scale...")
#         img_ = cv2.resize(gray,(64,48))
#         print("Resized...")
#         img_resized = cv2.imwrite(filename='saved_img-final.jpg', img=img_)
#         print("Image saved!")
        break
    
    
    elif key == ord('q'):
        print("Turning off camera.")
        webcam.release()
        print("Camera off.")
        print("Program ended.")
        cv2.destroyAllWindows()
        break

True
[[[ 57  35  38]
  [ 58  36  40]
  [ 56  39  35]
  ...
  [146 118  93]
  [157 119  96]
  [157 119  96]]

 [[ 55  35  38]
  [ 57  38  41]
  [ 60  37  36]
  ...
  [148 118  98]
  [154 120  98]
  [154 120  98]]

 [[ 58  41  37]
  [ 59  42  38]
  [ 58  41  37]
  ...
  [152 119  94]
  [155 122  98]
  [156 123  99]]

 ...

 [[ 16  21  20]
  [ 17  22  21]
  [ 14  19  23]
  ...
  [ 36  59  73]
  [ 42  55  71]
  [ 40  52  69]]

 [[ 16  23  22]
  [ 15  22  21]
  [ 19  20  24]
  ...
  [ 33  61  79]
  [ 37  61  76]
  [ 33  58  72]]

 [[ 11  25  18]
  [ 11  25  18]
  [ 19  21  23]
  ...
  [ 39  64  78]
  [ 30  63  78]
  [ 30  63  78]]]
True
[[[ 57  36  37]
  [ 55  35  36]
  [ 58  42  36]
  ...
  [150 115  98]
  [146 123  95]
  [146 123  95]]

 [[ 55  37  35]
  [ 56  38  36]
  [ 60  43  32]
  ...
  [148 116 101]
  [149 123  98]
  [149 123  98]]

 [[ 51  46  35]
  [ 52  47  36]
  [ 56  46  36]
  ...
  [151 120  97]
  [150 121  98]
  [150 121  98]]

 ...

 [[ 17  25  22]
  [ 16  24  21]
  [ 16  21

True
[[[178 170 147]
  [177 169 145]
  [176 167 146]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[175 172 148]
  [174 171 147]
  [171 170 147]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[175 170 145]
  [176 171 147]
  [173 175 147]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 66  95 104]
  [ 67  96 105]
  [ 72  97 109]
  ...
  [121 194 235]
  [119 175 225]
  [109 165 215]]

 [[ 68  95 111]
  [ 68  95 111]
  [ 72  97 109]
  ...
  [115 206 241]
  [124 196 237]
  [118 191 231]]

 [[ 67  98 113]
  [ 67  98 113]
  [ 74  97 109]
  ...
  [118 208 232]
  [113 205 236]
  [111 203 233]]]
True
[[[167 168 152]
  [168 169 153]
  [173 167 152]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[168 171 150]
  [168 171 150]
  [171 167 152]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[168 176 152]
  [169 177 153]
  [177 170 151]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 65 100 110]
  [ 65 100 110]
  [ 63  96

True
[[[191 188 170]
  [190 187 169]
  [191 188 161]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[191 190 165]
  [191 190 165]
  [193 191 164]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[187 193 160]
  [187 193 160]
  [190 195 160]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 83 113 113]
  [ 83 113 113]
  [ 83 114 109]
  ...
  [144 212 233]
  [134 195 235]
  [125 187 227]]

 [[ 85 111 116]
  [ 85 111 116]
  [ 83 114 111]
  ...
  [140 221 237]
  [138 211 238]
  [139 212 239]]

 [[ 83 110 119]
  [ 83 110 119]
  [ 85 112 114]
  ...
  [148 223 238]
  [136 223 241]
  [135 222 240]]]
True
[[[189 189 155]
  [189 189 155]
  [192 190 149]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[189 190 154]
  [189 190 154]
  [193 190 152]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[192 193 154]
  [193 195 156]
  [192 194 153]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 82 113 108]
  [ 83 114 109]
  [ 80 116

True
[[[189 191 152]
  [191 192 153]
  [195 191 162]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[193 191 155]
  [194 192 156]
  [193 191 164]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[193 194 157]
  [193 194 157]
  [195 191 162]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 87 112 113]
  [ 87 112 113]
  [ 83 114 111]
  ...
  [153 225 240]
  [148 201 234]
  [137 190 222]]

 [[ 85 114 109]
  [ 86 115 111]
  [ 83 113 113]
  ...
  [142 221 243]
  [151 213 244]
  [150 212 243]]

 [[ 85 111 116]
  [ 85 111 116]
  [ 85 111 116]
  ...
  [161 223 240]
  [156 218 244]
  [156 218 244]]]
True
[[[196 193 154]
  [196 193 154]
  [199 193 157]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[194 193 154]
  [194 193 154]
  [198 194 158]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[195 192 160]
  [195 192 160]
  [202 193 160]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 88 108 116]
  [ 89 109 117]
  [ 85 114

True
[[[193 190 156]
  [191 189 155]
  [193 187 163]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[193 189 160]
  [194 190 161]
  [194 189 162]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[193 193 159]
  [194 194 160]
  [196 194 160]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 78 110 116]
  [ 78 110 116]
  [ 80 112 111]
  ...
  [146 226 240]
  [143 200 234]
  [135 192 226]]

 [[ 81 112 116]
  [ 80 110 115]
  [ 81 114 111]
  ...
  [136 223 241]
  [146 213 243]
  [137 205 235]]

 [[ 84 108 118]
  [ 84 108 118]
  [ 85 114 109]
  ...
  [152 221 240]
  [150 222 240]
  [149 220 238]]]
True
[[[193 189 155]
  [193 189 155]
  [194 192 156]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[194 191 158]
  [193 190 156]
  [192 193 154]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[197 195 154]
  [197 195 154]
  [197 195 154]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 79 114 111]
  [ 80 116 112]
  [ 81 112

True
[[[191 192 153]
  [192 193 154]
  [192 193 156]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[194 193 154]
  [194 193 154]
  [192 193 156]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[191 194 157]
  [191 194 157]
  [195 194 156]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 80 110 115]
  [ 81 112 116]
  [ 83 112 114]
  ...
  [144 216 238]
  [146 199 231]
  [141 194 227]]

 [[ 83 110 110]
  [ 84 111 111]
  [ 82 110 108]
  ...
  [142 218 242]
  [147 211 237]
  [143 207 233]]

 [[ 83 113 113]
  [ 83 113 113]
  [ 85 112 114]
  ...
  [157 221 242]
  [153 221 244]
  [152 220 243]]]
True
[[[199 193 148]
  [199 193 148]
  [195 192 152]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[201 192 150]
  [201 192 150]
  [193 192 153]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[194 191 158]
  [194 191 158]
  [198 191 158]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 73 113 116]
  [ 72 112 115]
  [ 72 114

True
[[[192 192 158]
  [193 193 159]
  [199 195 152]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[188 193 152]
  [190 195 153]
  [197 195 154]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[193 194 150]
  [194 195 151]
  [195 195 154]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 79 113 114]
  [ 80 114 115]
  [ 79 113 114]
  ...
  [151 218 242]
  [138 201 230]
  [133 197 225]]

 [[ 81 113 113]
  [ 81 113 113]
  [ 81 113 113]
  ...
  [142 217 244]
  [140 214 239]
  [135 208 233]]

 [[ 80 114 108]
  [ 82 116 111]
  [ 81 115 109]
  ...
  [153 222 242]
  [141 223 244]
  [140 222 243]]]
True
[[[188 193 158]
  [186 191 156]
  [188 190 151]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[189 193 160]
  [188 192 159]
  [191 190 154]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[194 192 165]
  [193 191 164]
  [192 192 158]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 90 114 111]
  [ 90 114 111]
  [ 88 114

True
[[[191 192 149]
  [193 194 150]
  [193 190 156]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[191 192 153]
  [192 193 154]
  [192 190 161]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[189 193 160]
  [189 193 160]
  [193 193 159]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 88 112 108]
  [ 88 112 108]
  [ 84 111 111]
  ...
  [153 215 239]
  [152 197 233]
  [146 191 227]]

 [[ 86 113 108]
  [ 86 113 108]
  [ 84 114 107]
  ...
  [140 221 244]
  [152 212 239]
  [147 206 233]]

 [[ 77 115 111]
  [ 78 116 112]
  [ 78 116 112]
  ...
  [150 221 241]
  [151 221 244]
  [150 220 243]]]
True
[[[195 189 158]
  [195 189 158]
  [198 191 158]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[195 190 156]
  [196 191 158]
  [193 194 157]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 [[197 193 157]
  [197 193 157]
  [199 197 156]
  ...
  [251 254 251]
  [251 254 251]
  [251 254 251]]

 ...

 [[ 82 112 111]
  [ 82 112 111]
  [ 82 112

True
[[[32 30 42]
  [33 31 43]
  [30 31 56]
  ...
  [46 53 81]
  [43 55 87]
  [45 57 89]]

 [[25 30 48]
  [26 32 49]
  [25 31 53]
  ...
  [42 53 86]
  [39 55 88]
  [42 58 92]]

 [[28 33 53]
  [28 33 53]
  [28 31 58]
  ...
  [45 56 91]
  [47 55 92]
  [48 56 93]]

 ...

 [[55 38 59]
  [59 43 64]
  [42 55 62]
  ...
  [39 52 73]
  [43 49 78]
  [44 50 79]]

 [[55 45 62]
  [56 46 64]
  [41 55 59]
  ...
  [36 52 79]
  [37 50 79]
  [36 48 78]]

 [[47 46 71]
  [47 46 71]
  [43 49 66]
  ...
  [32 49 78]
  [33 49 74]
  [33 49 74]]]
True
[[[16 35 53]
  [17 37 54]
  [23 38 54]
  ...
  [42 56 88]
  [44 59 89]
  [45 60 90]]

 [[ 9 35 52]
  [10 37 53]
  [21 37 55]
  ...
  [41 57 91]
  [43 58 95]
  [44 60 96]]

 [[23 36 57]
  [23 36 57]
  [23 34 57]
  ...
  [46 59 89]
  [42 61 94]
  [44 62 95]]

 ...

 [[39 52 62]
  [39 52 62]
  [43 47 62]
  ...
  [39 49 72]
  [35 48 75]
  [37 50 78]]

 [[45 53 58]
  [44 52 57]
  [41 49 59]
  ...
  [40 49 75]
  [43 48 81]
  [43 48 81]]

 [[47 51 60]
  [46 50 59]
  [35 

# 2. Calibrate Camera
Get the camera parameters. Need these (fx, fy, cx, cy) to undistort images and more accurately calculate pose

In [9]:
from __future__ import print_function
import numpy as np
import cv2
import argparse
import os
from matplotlib import pyplot as plt



def get_calibration_parameters(images_dir, rows, cols, size, show_detections=True):
    """This function receives several chessboard photos taken at different angles, 
    and calculates the calibration parameters specific to the camara being used. 
    These parameters are then used to undistort images."""
    
    

    path = images_dir

    options_dict = dict()
    options_dict['filenames'] = [os.path.join(path, f) for f in os.listdir(images_dir)]
    options_dict['rows'] = rows
    options_dict['cols'] = cols
    options_dict['size'] = size
    options_dict['show_detections'] = show_detections
    
    patternsize = (options_dict['rows'], options_dict['cols'])
    
    # termination criteria
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

    sz = options_dict['size']

    x = np.arange(patternsize[0])*sz
    y = np.arange(patternsize[1])*sz

    xgrid, ygrid = np.meshgrid(x, y)
    zgrid = np.zeros_like(xgrid)
    opoints = np.dstack((xgrid, ygrid, zgrid)).reshape((-1, 1, 3)).astype(np.float32)

    imagesize = None

    win = 'Calibrate'
    cv2.namedWindow(win)

    ipoints = []


    for filename in options_dict['filenames']:

        rgb = cv2.imread(filename)
        
        if rgb is None:
            print('warning: error opening {}, skipping'.format(filename))
            continue

        cursize = (rgb.shape[1], rgb.shape[0])
        
        if imagesize is None:
            imagesize = cursize
        else:
            assert imagesize == cursize

        print('loaded ' + filename + ' of size {}x{}'.format(*imagesize))

        if len(rgb.shape) == 3:
            gray = cv2.cvtColor(rgb, cv2.COLOR_RGB2GRAY)
        else:
            gray = rgb


        retval, corners = cv2.findChessboardCorners(gray, patternsize)

        if options_dict['show_detections']:
            display = cv2.cvtColor(gray, cv2.COLOR_GRAY2RGB)
            cv2.drawChessboardCorners(display, patternsize, corners, retval)
            cv2.imshow(win, display)
            # while cv2.waitKey(5) not in range(128): pass

        if not retval:
            print('warning: no chessboard found in {}, skipping'.format(filename))
        else:
            print('pattern found in {}'.format(filename))
            ipoints.append( corners )
            
            corners2=cv2.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
#             imgpoints.append(corners)
            # Draw and display the corners
            cv2.drawChessboardCorners(rgb, (9,6), corners2, retval)
            cv2.imshow('rgb', rgb)
            cv2.waitKey(500)


    flags = (cv2.CALIB_ZERO_TANGENT_DIST |
             cv2.CALIB_FIX_K1 |
             cv2.CALIB_FIX_K2 |
             cv2.CALIB_FIX_K3 |
             cv2.CALIB_FIX_K4 |
             cv2.CALIB_FIX_K5 |
             cv2.CALIB_FIX_K6)

    opoints = [opoints] * len(ipoints)

    retval, K, dcoeffs, rvecs, tvecs = cv2.calibrateCamera(opoints, ipoints, imagesize,
                                                           None, None)

#     assert( np.all(dcoeffs == 0) )
    
    fx = K[0,0]
    fy = K[1,1]
    cx = K[0,2]
    cy = K[1,2]

    params = (fx, fy, cx, cy)

    print()
    print('all units below measured in pixels:')
    print('  fx = {}'.format(K[0,0]))
    print('  fy = {}'.format(K[1,1]))
    print('  cx = {}'.format(K[0,2]))
    print('  cy = {}'.format(K[1,2]))
    print()
    print('pastable into Python:')
    print('  fx, fy, cx, cy = {}'.format(repr(params)))
    print()
    
    return(retval, K, dcoeffs, rvecs, tvecs)






In [11]:
calibration_parameters = get_calibration_parameters('/home/sarita/Documents/SeniorD/apriltag_detection/calibration_images/webcam/chessboard/large_hor',9, 6, 1.0)
ret, mtx, dist, rvecs, tvecs = calibration_parameters

loaded /home/sarita/Documents/SeniorD/apriltag_detection/calibration_images/webcam/chessboard/large_hor/2saved_img.jpg of size 640x480
pattern found in /home/sarita/Documents/SeniorD/apriltag_detection/calibration_images/webcam/chessboard/large_hor/2saved_img.jpg
loaded /home/sarita/Documents/SeniorD/apriltag_detection/calibration_images/webcam/chessboard/large_hor/3saved_img.jpg of size 640x480
pattern found in /home/sarita/Documents/SeniorD/apriltag_detection/calibration_images/webcam/chessboard/large_hor/3saved_img.jpg
loaded /home/sarita/Documents/SeniorD/apriltag_detection/calibration_images/webcam/chessboard/large_hor/1saved_img.jpg of size 640x480
pattern found in /home/sarita/Documents/SeniorD/apriltag_detection/calibration_images/webcam/chessboard/large_hor/1saved_img.jpg
loaded /home/sarita/Documents/SeniorD/apriltag_detection/calibration_images/webcam/chessboard/large_hor/4saved_img.jpg of size 640x480
pattern found in /home/sarita/Documents/SeniorD/apriltag_detection/calibr

### 2.1 (Optional) Undistort apriltag images:

This method reads an image from image_path, and saves an undistorted copy in 'undistorted' folder within that directory.

**For viewing and debbuging purposes only. Method 2 for pose estimation includes image "undistortion" within it, so no need to feed in an "undistorted" image.**

In [90]:
image_path = '/home/sarita/Documents/SeniorD/calibration_images/webcam/apriltags/original'

for filename in os.listdir(image_path):
    print("Currently reading", filename)
    img = cv2.imread(os.path.join(image_path, filename))
    h,  w = img.shape[:2]
    newcameramtx, roi=cv2.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))

    # undistort
    dst = cv2.undistort(src=img, cameraMatrix=mtx, distCoeffs=dist, newCameraMatrix=newcameramtx)
    # crop the image
    x, y, w, h = roi
    dst = dst[y:y+h, x:x+w]
    cv2.imwrite(str(image_path+ "/undistorted/"+"".join(filename.split('.')[:-1]) + '_undistorted.jpg'), dst)


loaded /home/sarita/Documents/SeniorD/calibration_images/webcam/chessboard/large_hor/2saved_img.jpg of size 640x480
pattern found in /home/sarita/Documents/SeniorD/calibration_images/webcam/chessboard/large_hor/2saved_img.jpg
loaded /home/sarita/Documents/SeniorD/calibration_images/webcam/chessboard/large_hor/3saved_img.jpg of size 640x480
pattern found in /home/sarita/Documents/SeniorD/calibration_images/webcam/chessboard/large_hor/3saved_img.jpg
loaded /home/sarita/Documents/SeniorD/calibration_images/webcam/chessboard/large_hor/1saved_img.jpg of size 640x480
pattern found in /home/sarita/Documents/SeniorD/calibration_images/webcam/chessboard/large_hor/1saved_img.jpg
loaded /home/sarita/Documents/SeniorD/calibration_images/webcam/chessboard/large_hor/4saved_img.jpg of size 640x480
pattern found in /home/sarita/Documents/SeniorD/calibration_images/webcam/chessboard/large_hor/4saved_img.jpg
loaded /home/sarita/Documents/SeniorD/calibration_images/webcam/chessboard/large_hor/6saved_img.

# 3. Identify AprilTag ID:

### 3.1 Method 1: Requires additional calculation of pose based on apriltag corners detection
Using the apriltag module on Pypi: https://pypi.org/project/apriltag/
Provides no out of the box pose estimation methods. 
I would have to write the similar triangle math to estimate pose. Better look for an off the shelf solution.

**check out method 2, is much better**

In [92]:
import apriltag
import cv2

images_path = '/home/sarita/Documents/SeniorD/calibration_images/webcam/apriltags/undistorted'
filename = 'april7_undistorted.jpg'

img = cv2.imread(os.path.join(images_path, filename), cv2.IMREAD_GRAYSCALE)
detector = apriltag.Detector()
result = detector.detect(img)

print("The ID of ", filename, "is", result[0].tag_id, "\n\n")
print("Corners Found are: \n", result[0].corners)


tl_hor = int(round(result[0].corners[0][0]))
tl_ver = int(round(result[0].corners[0][1]))

tr_hor = int(round(result[0].corners[1][0]))
tr_ver = int(round(result[0].corners[1][1]))

br_hor = int(round(result[0].corners[2][0]))
br_ver = int(round(result[0].corners[2][1]))

bl_hor = int(round(result[0].corners[3][0]))
bl_ver = int(round(result[0].corners[3][1]))

#draw corners in image
#must provide vertical,horizontal coordinates
img[tl_ver, tl_hor] = 255
img[tr_ver, tr_hor] = 255
img[br_ver, br_hor] = 255
img[bl_ver, bl_hor] = 255

cv2.imwrite(str(image_path+ "/"+ "".join(filename.split('.')[:-1]) + '_corners.jpg'), img)
print(img.shape)



The ID of  april7_undistorted.jpg is 7 


Corners Found are: 
 [[ 26.71990776 307.64584351]
 [192.20863342 222.24040222]
 [348.36398315 288.62301636]
 [209.796875   407.537323  ]]
(438, 595)


### 3.2 Method 2: Includes pose estimation

AprilRobotics provides this guide, primarily focused on C++ solutions.
https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation

On it they reference these python bindings by duckietown:
https://github.com/duckietown/apriltags3-py

Cloned and followed readme to build the C++ Apriltags library on terminal.

**A note: looks like there are several hyperparameters to the detector that may improve accuracy when tuned. Must simulate environment of competition and test on different combinations of hyperparameters.**

Outputs pose as:
* A 3x3 rotation Matrix of the pose estimate
* A 3x1 vector translation of the pose estimate
* A scalar indicating the object-space error of the estimate


In [4]:
import sys
path_to_library = '/home/sarita/Documents/SeniorD/apriltag_detection/apriltags3-py' #Paste here the path to apriltags3-py you cloned
sys.path.insert(1, path_to_library)
import apriltags3
import cv2

# Detector parameters explained in https://github.com/duckietown/apriltags3-py
at_detector = apriltags3.Detector(searchpath=[str(path_to_library)+'/apriltags/lib'], 
                       families='tag36h11',
                       nthreads=1,
                       quad_decimate=1.0,
                       quad_sigma=0.0,
                       refine_edges=1,
                       decode_sharpening=0.25,
                       debug=0)

# path to apriltag image to load and detect
image_path = "/home/sarita/Documents/SeniorD/apriltag_detection/calibration_images/webcam/apriltags/original/april7.jpg" 
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

camera_parameters = [680.9565272862395, 678.9601430884998, 320.50156915761715, 233.43506067483017]

tags = at_detector.detect(img, estimate_tag_pose=True, camera_params=camera_parameters, tag_size=0.172)

print(tags)


[Detection object:
tag_family = b'tag36h11'
tag_id = 7
hamming = 0
decision_margin = 88.25628662109375
homography = [[ 1.08900711e+02  7.73157543e+01  2.10410463e+02]
 [-1.26027511e+01  2.26224164e+01  3.24913644e+02]
 [ 1.27690144e-01 -6.59294160e-02  1.00000000e+00]]
center = [210.41046277 324.91364409]
corners = [[221.76319885 446.61154175]
 [373.55584717 315.45083618]
 [202.74082947 242.69749451]
 [ 25.7865963  335.62225342]]
pose_R = [[ 0.55399485  0.8298627  -0.0664651 ]
 [-0.34441196  0.3011389   0.88921076]
 [ 0.75793806 -0.4697268   0.45264403]]
pose_t = [[-0.07896993]
 [ 0.06437786]
 [ 0.48406678]]
pose_err = 4.581818094184746e-06
]
